@PORT = 3000

@HOST = http://localhost:{{PORT}}
GET {{HOST}}/api/users


###
GET {{HOST}}/api/users/1
Content-Type: application/json


###
POST {{HOST}}/api/users
Content-Type: application/json

{
    "nombre": "Paco",
    "email": "pacopaquillo@sontumonaguiñllo.",
    "imagen": "imagen.jpg"
}
###
PUT {{HOST}}/api/users/2
Authorization: API-KEY
Content-Type: application/json

{
    "nombre": "Juan Perez",
    "email": "pacopaquillo@sontumonaguiñllo.",
    "imagen": "imagen"
}
###
DELETE {{HOST}}/api/users/1
Authorization: API-KEY

